name: CI/CD pipeline

on:
  push:
    branches:
      - main
      
permissions:
  actions: read
  contents: read     
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m venv venv  # Crear el entorno virtual 'venv'
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar pruebas unitarias con pytest
      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest -s tests/

      # Ejecutar pruebas de cobertura con pytest
      - name: Run pytest Coverage
        run: |
          source venv/bin/activate
          pytest --cov tests/

      # Ejecutar pruebas de comportamiento con behave para español
      - name: Run behave - español tests
        run: |
          source venv/bin/activate
          behave --tags=@español

      # Ejecutar pruebas de comportamiento con behave para inglés
      - name: Run behave - ingles tests
        run: |
          source venv/bin/activate
          behave --tags=@ingles

      # Ejecutar pruebas de comportamiento para criterios nuevos
      - name: Run behave - Criterios Nuevos
        run: |
          source venv/bin/activate
          behave --tags=@criterio_nuevo

      # generar coverage.xml
      - name: Run Pytest and generate coverage report
        run: |
          source venv/bin/activate
          pytest --cov=tests/ --cov-report=xml

      # generar behave-report.xml
      - name: Run Behave and generate behave report
        run: |
          source venv/bin/activate
          behave --format json --outfile behave-report.json

      # Subir coverage.xml como artifact
      - name: Upload Pytest Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage-report
          path: coverage.xml

      # Subir behave-report.xml como artifact
      - name: Upload Behave Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: behave-report
          path: behave-report.json


# Despliegue
# deploy:
#   runs-on: ubuntu-latest
#   needs: test
#
#   steps:
#     # Pasos para el despliegue aquí


